version: '3.2'
services:

  #MSSQL Service
  msdb:
    image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    container_name: db_mssql
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "elessDB18"
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/var/opt/mssql/data
      #- ./bak/data.bak:/tmp/data.bak
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local